src/KV/MyBundle/Entity/Image.php
<?php

namespace KV\MyBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;



/**
 * Image
 *
 * @ORM\Table(name="image")
 * @ORM\Entity(repositoryClass="KV\MyBundle\Repository\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;


    private $file;

    //Permet de stocker le nom du fichier de maniere temporaire
    private $tempFilename;



    public function getFile()
    {
        return $this->file;
    }

    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;

        if($this->url === null)
        {
            $this->tempFilename = $this->url;

            $this->url = null;
            $this->alt = null;
        }
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function preUpload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
        if ( $this->file === null) {
            return;
        }

        // Le nom du fichier est son id, on doit juste stocker également son extension
        $this->url = $this->file->guessExtension();

        // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
        $this->alt = $this->file->getClientOriginalName();


    }

    /**
     * @ORM\PostPersist
     * @ORM\PostUpdate
     */
    public function upload()
    {
        if($this->file === null)
        {
            return;
        }

        // Si on avait un ancien fichier, on le supprime
        if (null !== $this->tempFilename) {
            $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }

        // On déplace le fichier envoyé dans le répertoire de notre choix
        $this->file->move(
            $this->getUploadRootDir(), // Le répertoire de destination
            $this->id.'.'.$this->url   // Le nom du fichier à créer, ici « id.extension »
        );
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempFilename)) {
            // On supprime le fichier
            unlink($this->tempFilename);
        }
    }


    public function getUploadDir()
    {
        return 'uploads/img';
    }

    public function getUploadRootDir()
    {
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    public function getWebPath()
    {
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
    }


    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url.
     *
     * @param string $url
     *
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url.
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt.
     *
     * @param string $alt
     *
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt.
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }
}

src/KV/MyBundle/Form/AdvertType.php
<?php

namespace KV\MyBundle\Form;

use KV\MyBundle\Repository\CategoryRepository;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdvertType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        //pattern category
        $pattern = 'D%';

        $builder
            ->add('date',      DateType::class)
            ->add('title',     TextType::class)
            ->add('content',   TextareaType::class)
            ->add('author',    TextType::class)
            ->add('image',     ImageType::class)
            ->add('categories',EntityType::class, array(
                'class'   => 'KV\MyBundle\Entity\Category',
                'choice_label'    => 'name',
                'multiple' => false,
                'mapped' => false,
                'query_builder' => function(CategoryRepository $repository) use($pattern){
                    return $repository->getLikeQueryBuilder($pattern);
                }
            ))
            ->add('save',      SubmitType::class);


        //fonction qui écoute un évenement pour le champ PUBLISHED
        $builder->addEventListener(
          FormEvents::PRE_SET_DATA,

          function (FormEvent $event) {
              $advert = $event->getData();

              if(null === $advert) {
                  return;
              }

              if(!$advert->getPublished() || null === $advert->getId()){
                  $event->getForm()->add('published', CheckboxType::class, array(
                      'required' => false
                  ));
              } else {
                  $event->getForm()->remove('published');
              }
          }
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'KV\MyBundle\Entity\Advert'
        ));
    }

}

src/KV/MyBundle/Controller/AdvertController.php
<?php

// src/OC/PlatformBundle/Controller/AdvertController.php

namespace KV\MyBundle\Controller;

use KV\MyBundle\Entity\Advert;
use KV\MyBundle\Entity\AdvertSkill;
use KV\MyBundle\Entity\Application;
use KV\MyBundle\Entity\Image;
use KV\MyBundle\Form\AdvertEditType;
use KV\MyBundle\Form\AdvertType;
use KV\MyBundle\Repository\AdvertRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;


class AdvertController extends Controller
{

    /**
     * @Route("/{page}", name="kv_platform_home",defaults={"page"=1},requirements={"page"="\d*"})
     */
    public function indexAction($page)
    {
        if ($page < 1) {
            throw new NotFoundHttpException('Page "'.$page.'" inexistante.');
        }

        $em = $this->getDoctrine()->getManager();
        $nbPerPage = 5;

        $listAdverts = $em->getRepository('KVMyBundle:Advert')->getAdverts($page,$nbPerPage);

        // On calcule le nombre total de pages grâce au count($listAdverts) qui retourne le nombre total d'annonces
        $nbPages = ceil(count($listAdverts) / $nbPerPage);

        // Si la page n'existe pas, on retourne une 404
        if ($page > $nbPages) {
            throw $this->createNotFoundException("La page ".$page." n'existe pas.");
        }

        return $this->render('@KVMy/Advert/index.html.twig', array(
            'listAdverts' => $listAdverts,
            'nbPages'     => $nbPages,
            'page'        => $page
            ));
    }



    /**
     * @Route("/advert/{id}", name="kv_platform_view",requirements={"id"="\d+"})
     */
    public function viewAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        // On récupère l'entité correspondante à l'id $id
        $advert = $em->getRepository('KVMyBundle:Advert')->find($id);


        // $advert est donc une instance de OC\PlatformBundle\Entity\Advert
        // ou null si l'id $id  n'existe pas, d'où ce if :
        if (null === $advert) {
            throw new NotFoundHttpException("L'annonce d'id ".$id." n'existe pas.");
        }

        $applications = $em->getRepository('KVMyBundle:Application')->findBy(
            array(
                'advert' => $advert
            )
        );

        $listAdvertSkills = $em->getRepository('KVMyBundle:AdvertSkill')->findBy(
            array(
                'advert' => $advert
            )
        );

        // Le render ne change pas, on passait avant un tableau, maintenant un objet
        return $this->render('@KVMy/Advert/view.html.twig', array(
            'advert' => $advert,
            'applications' => $applications,
            'listAdvertSkills' => $listAdvertSkills
        ));
    }


    /**
     * @Route("/add", name="kv_platform_add")
     */
    public function addAction(Request $request)
    {
        if(!$this->get('security.authorization_checker')->isGranted('ROLE_AUTEUR')){
            throw  new AccessDeniedException('Accès limité aux auteurs');
        }


        // On crée un objet Advert
        $advert = new Advert();

        $advert->setEmail('simokevin95@outlook.fr');

        // On crée le formulaire grâce au service form factory
        $form = $this->createForm(AdvertType::class, $advert);

        if($request->isMethod('POST') && $form->handleRequest($request)->isValid() )
        {
            $em = $this->getDoctrine()->getManager();
            $em->persist($advert);
            $em->flush();

            $request->getSession()->getFlashBag()->add('notice', 'Annonce bien enregistrée.');

            return $this->redirectToRoute('kv_platform_view',array('id' => $advert->getId()));
        }

        return $this->render('@KVMy/Advert/add.html.twig', array(
            'form' => $form->createView(),
        ));

    }



    /**
     * @Route("/edit/{id}", name="kv_platform_edit",requirements={"id"="\d+"})
     */
    public function editAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $advertToUpdate = $em->getRepository('KVMyBundle:Advert')->find($id);

        if($advertToUpdate === null) {
            throw new NotFoundHttpException("L'annonce d'id : ".$id." n'existe pas");
        }

        $form = $this->createForm(AdvertEditType::class, $advertToUpdate);

        if($request->isMethod('POST') && $form->handleRequest($request)->isValid() )
        {
            $em = $this->getDoctrine()->getManager();
            $em->persist($advertToUpdate);
            $em->flush();

            $request->getSession()->getFlashBag()->add('notice', 'Annonce bien Modifiée.');

            return $this->redirectToRoute('kv_platform_view',array('id' => $advertToUpdate->getId()));
        }

        return $this->render('@KVMy/Advert/edit.html.twig', array(
            'form' => $form->createView(),
            'advert' => $advertToUpdate
        ));
    }


    /**
     * @Route("/edit_cat/{id}", name="kv_platform_edit_cat",requirements={"id"="\d+"})
     */
    public function editCatAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $advert = $em->getRepository('KVMyBundle:Advert')->find($id);

        if($advert === null) {
            throw new NotFoundHttpException("L'annonce d'id : ".$id." n'existe pas");
        }

        $listCategories = $em->getRepository('KVMyBundle:Category')->findAll();
        foreach ($listCategories as $category){
            $advert->removeCategory($category);
        }

        $em->flush();
        $request->getSession()->getFlashBag()->add('deleted','Catégories bien supprimées !');




        return $this->redirectToRoute('kv_platform_view',array('id' => $advert->getId()));
    }



    /**
     * @Route("/delete/{id}", name="kv_platform_delete",requirements={"id"="\d+"})
     */
    public function deleteAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        $advert = $em->getRepository('KVMyBundle:Advert')->find($id);

        if($advert === null) {
            throw new NotFoundHttpException("L'annonce d'id : ".$id." n'existe pas");
        }

        $form = $this->get('form.factory')->create();

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid())
        {
            $em->remove($advert);
            $em->flush();

            $request->getSession()->getFlashBag()->add('info','L\'annonce a bien été supprimée' );

            return $this->redirectToRoute('kv_platform_home');
        }

        return $this->render('@KVMy/Advert/delete.html.twig', array(
            'advert' => $advert,
            'form' => $form->createView()
        ));
    }



    public function menuAction()
    {
        $em = $this->getDoctrine()->getManager();

        $listAdverts = $em->getRepository('KVMyBundle:Advert')->findBy(
            array(),
            array('date' => 'desc')
        );

        return $this->render('@KVMy/Advert/menu.html.twig', array(
            'listAdverts' => $listAdverts
        ));
    }

    /**
     * @Route("/purge/{days}", name="kv_platform_purge",requirements={"days"="\d+"})
     */
    public function purgeAction( $days )
    {

    }



}

src/KV/MyBundle/Resources/views/Advert/add.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/edit.html.twig #}

{% extends "@KVMy/layout.html.twig" %}

{% block title %}
    Ajouter une annonce
{% endblock %}

{% block kvplatform_body %}

    <h2>Ajouter une annonce</h2>

    {{ include("@KVMy/Advert/form.html.twig") }}

    <p>
        Vous allez enregistrer une nouvelle annonce.
    </p>


{% endblock %}

src/KV/MyBundle/Resources/views/Advert/delete.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/edit.html.twig #}

{% extends "@KVMy/layout.html.twig" %}

{% block title %}
    Supprimer une annonce
{% endblock %}

{% block kvplatform_body %}

    <h2>Supprimer cette annonce</h2>

    <p>
      Etes vous certain de vouloir supprimer l'annonce "{{ advert.title }}"
    </p>

    {# On met l'id de l'annonce dans la route de l'action du formualaire #}
    <form action="{{ path('kv_platform_delete', {'id': advert.id}) }}" method="post">
        <a href="{{ path('kv_platform_view', {'id': advert.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à l'annonce
        </a>

        <input type="submit" value="Supprimer" class="btn btn-danger"/>

        {{ form_rest(form) }}
    </form>

{% endblock %}

src/KV/MyBundle/Resources/views/Advert/edit.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/edit.html.twig #}

{% extends "@KVMy/layout.html.twig" %}

{% block title %}
     Modifier une annonce
{% endblock %}

{% block kvplatform_body %}

    <h2>Modifier une annonce</h2>

    {{ include("@KVMy/Advert/form.html.twig") }}

    <p>
        Vous éditez une annonce déjà existante, merci de ne pas changer
        l'esprit général de l'annonce déjà publiée.
    </p>

    <p>

        {% if advert is defined  %}
        <a href="{{ path('kv_platform_view', {'id': advert.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à l'annonce
        </a>
        {% else  %}
        <a href="{{ path('kv_platform_home') }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à l'acceuil ( pas d'annonce à modifier )
        </a>
        {% endif  %}
    </p>

{% endblock %}

src/KV/MyBundle/Resources/views/Advert/form.html.twig
{# src/KV/MyBundle/Resources/views/Advert/form.html.twig #}

{# Cette vue n'hérite de personne, elle sera incluse par d'autres vues qui,
   elles, hériteront probablement du layout. Je dis « probablement » car,
   ici pour cette vue, on n'en sait rien et c'est une info qui ne nous concerne pas. #}


<h3>Formulaire d'annonces</h3>


<div class="well">
    {{ form_start(form) }}

    {# Les erreurs générales du formulaire. #}
    {{ form_errors(form) }}

    {# Génération manuelle et éclatée : #}
    {% if form.date is defined %}
    <div class="form-group">
        <div class="form-group" >
            <div class="col-sm-3">
                {{ form_label(form.date) }}
            </div>
            <div class="col-sm-9">
                {{ form_widget(form.date) }}
            </div>
        </div>
    </div>
    {% endif %}

    <div class="form-group">
        {{ form_label(form.title, "Titre de l'annonce", {'label_attr': {'class': 'col-sm-3'}}) }}

        <div class="col-sm-9">
            {{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.title) }}
        </div>
    </div>

    <div class="form-group">
        {{ form_label(form.content, "Contenu de l'annonce", {'label_attr': {'class': 'col-sm-3'}}) }}

        <div class="col-sm-9">
            {{ form_widget(form.content) }}
            {{ form_errors(form.content) }}
        </div>
    </div>

    <div class="form-group">
        {{ form_label(form.author, "Auteur de l'annonce", {'label_attr': {'class': 'col-sm-3'}}) }}

        <div class="col-sm-9">
            {{ form_widget(form.author) }}
            {{ form_errors(form.author) }}
        </div>
    </div>

    <div class="form-group">
        {{ form_label(form.image, "Image de l'annonce", {'label_attr': {'class': 'col-sm-3'}}) }}

        <div class="col-sm-9">
            {{ form_widget(form.image) }}
            {{ form_errors(form.image) }}
        </div>
    </div>

    {% if form.categories is defined %}
    <div class="form-group" >
        <div class="col-sm-3">
        {{ form_label(form.categories) }}
        </div>
        <div class="col-sm-9">
            {{ form_widget(form.categories) }}
        </div>
    </div>
    {% endif %}

{#    <a href="#" id="add_category" class="btn btn-default">Ajouter une catégorie</a>#}

    {% if form.published is defined %}
    <div class="form-group">
        <div class="col-sm-offset-10">
            {{ form_row(form.published) }}
        </div>
    </div>
    {% endif %}



    {# Pour le bouton, pas de label ni d'erreur, on affiche juste le widget #}
    {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}

    {# Fermeture de la balise <form> du formulaire HTML #}
    {{ form_end(form) }}
</div>

src/KV/MyBundle/Resources/views/Advert/index.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/index.html.twig #}

{% extends "@KVMy/layout.html.twig" %}

{% block title %}
    Accueil - {{ parent() }}
{% endblock %}

{% block kvplatform_body %}

    <h2>Liste des annonces</h2>

    <ul>
        {% for advert in listAdverts %}
            <li>
                <a href="{{ path('kv_platform_view', {'id': advert.id}) }}">
                    {{ advert.title }}
                </a>
                par {{ advert.author }},
                le {{ advert.date|date('d/m/Y') }}
            </li>
        {% else %}
            <li>Pas (encore !) d'annonces</li>
        {% endfor %}
    </ul>
    <ul class="pagination">
        {# PAGINATION #}
        {# On utilise la fonction range(a, b) qui crée un tableau de valeurs entre a et b #}
        {% for p in range(1, nbPages) %}
            <li{% if p == page %} class="active"{% endif %}>
                <a href="{{ path('kv_platform_home', {'page': p}) }}">{{ p }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

src/KV/MyBundle/Resources/views/Advert/menu.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/menu.html.twig #}

{# Ce template n'hérite de personne,
   tout comme le template inclus avec {{ include() }}. #}

<ul class="nav nav-pills nav-stacked">
    {% for advert in listAdverts|slice(0,4) %}
        <li>
            <a href="{{ path('kv_platform_view', {'id': advert.id}) }}">
                {{ advert.title }}
            </a>
        </li>
    {% endfor %}
</ul>

src/KV/MyBundle/Resources/views/Advert/view.html.twig
{# src/OC/PlatformBundle/Resources/view/Advert/view.html.twig #}

{% extends "@KVMy/layout.html.twig" %}

{% block title %}
    Lecture d'une annonce
{% endblock %}

{% block kvplatform_body %}

    {# si l'annonce a une image associée #}
    {% if advert.image is not null %}
        <img
                src="{{ asset(advert.image.webPath) }}"
                alt="{{ advert.image.alt }}"
                height="4%" width="16%"
        />
    {% endif %}
    <h2>{{ advert.title }}</h2>
    <i>Par {{ advert.author }}, le {{ advert.date|date('d/m/Y') }}</i>

    <div class="well">
        {{ advert.content }}
    </div>

    <p>
        <a href="{{ path('kv_platform_home') }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à la liste
        </a> &nbsp;
        <a href="{{ path('kv_platform_edit', {'id': advert.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-edit"></i>
            Modifier l'annonce
        </a> &nbsp;
        <a href="{{ path('kv_platform_edit_cat', {'id': advert.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-edit"></i>
            Supprimer catégories
        </a>
        <a href="{{ path('kv_platform_delete', {'id': advert.id}) }}" class="btn btn-danger">
            <i class="glyphicon glyphicon-trash"></i>
            Supprimer l'annonce
        </a>
    </p>
    <br>



    {# Affichage d'un flash bag #}
    {% for messages in app.flashes(['edited','noEdited','deleted']) %}
        {% for message in messages %}
            <div class="alert alert-info" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}


    {% if not advert.categories.empty %}
        <p>
            Cette annonce est parue dans les catégories suivantes :
            {% for category in advert.categories %}
                {{ category.name }} {% if not loop.last %} , {% endif %}
            {% endfor %}
        </p>
    {% endif %}


    {% if listAdvertSkills|length > 0 %}
        <div>
            Cette annonce requiert les compétences suivantes :
            <ul>
                {% for advertSkill in listAdvertSkills %}
                    <li>{{ advertSkill.skill.name }} : niveau {{ advertSkill.level }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    <div class="page-header">
        <h3> Les candidatures associées </h3>
    </div>

    <div class="list-group">
    {% for application in applications %}
            <h4 class="list-group-item-heading">Candidat(e) : {{ application.author }}</h4>
            <p class="list-group-item-text">
                {{ application.content }}
            </p>
            <i style="color: #aacd4e">le {{ application.date|date('d/m/Y') }}</i>
        <hr>
    {% else %}
        <div class="alert alert-info" role="alert">
            Pas (encore !) de candidatures
        </div>
    {% endfor %}
    </div>



{% endblock %}